name: statapp
channels:
  - conda-forge
  - default
dependencies:
  - python
  - ipykernel
  - ipywidgets
  - jupyterlab=2
  - jupyterlab-git
  - nbdime  
  - nodejs
  - numpy
  - pandas
  - pip
  - matplotlib
  - seaborn
  - scikit-learn
  - flake8
  - python-graphviz
  - tqdm
  - py-xgboost=0.90
